version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
      args: 
        VARIANT: 11-bullseye
    command: sleep infinity
    volumes:
      - .:/workspace:cached